Edited RPC-protocol description
wirenboard/mqtt-rpc pull request #3
Opened 2022-10-13 06:26 UTC by rkochkin

Немного переоформил и структурировал описание протокола. 
Добавил форматирование, где не было.

2022-10-13 06:47 UTC, KraPete approved these changes

2022-10-13 15:01 UTC, webconn requested changes
С устаревшими ссылками не знаю, что делать. Можно удалить совсем, можно обновить (но вести они будут на приватные репозитории)

2022-10-13 15:12 UTC, rkochkin commented on README.en.md
> +* C++ (as part of libwbmqtt): https://github.com/contactless/libwbmqtt/blob/master/common/mqttrpc.h
Сделать ссылки на приветные репозитории?

2022-10-14 10:36 UTC, rkochkin commented on README.en.md
> +* C++ (as part of libwbmqtt): https://github.com/contactless/libwbmqtt/blob/master/common/mqttrpc.h
Убрал ссылки

2022-10-17 11:30 UTC, webconn approved these changes

2022-10-17 12:33 UTC, merged